# Generated by Django 6.1 on 2026-09-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('COUNTRY', 'Country'), ('PROVINCE', 'Province'), ('DISTRICT', 'District'), ('MUNICIPALITY', 'Municipality')], default='DISTRICT', max_length=20)),
                ('map_path', models.TextField(blank=True)),
                ('label_x', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('label_y', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='registry.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('MORGUE', 'Morgue'), ('POLICE_POST', 'Police post'), ('ARMY_CAMP', 'Army camp'), ('NGO', 'Relief organisation')], default='HOSPITAL', max_length=20)),
                ('is_connected', models.BooleanField(default=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisations', to='registry.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('LANDSLIDE', 'Landslide'), ('GLACIER_COLLAPSE', 'Glacier collapse'), ('FIRE', 'Fire'), ('CYCLONE', 'Cyclone')], max_length=20)),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PREPARING', max_length=20)),
                ('occurred_on', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('regions', models.ManyToManyField(blank=True, related_name='events', to='registry.region')),
            ],
            options={
                'ordering': ['-occurred_on'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='only_one_primary_event')],
            },
        ),
    ]
