# Generated by Django 6.1 on 2026-09-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_event_hotline_hours_event_hotline_phone_eventfigure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='secondary_calendar',
            field=models.CharField(choices=[('NONE', 'Gregorian only'), ('BIKRAM_SAMBAT', 'Bikram Sambat and Gregorian')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
