# Generated by Django 6.1 on 2026-09-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_event_secondary_calendar_event_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPersonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('also_known_as', models.CharField(blank=True, help_text='Nicknames, or other spellings of the name.', max_length=200)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Not known')], default='UNKNOWN', max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('build', models.CharField(choices=[('SLIGHT', 'Slight'), ('MEDIUM', 'Medium'), ('HEAVY', 'Heavy'), ('UNKNOWN', 'Not known')], default='UNKNOWN', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_location', models.CharField(blank=True, max_length=200)),
                ('clothing_description', models.TextField(blank=True)),
                ('distinguishing_marks', models.TextField(blank=True, help_text='Scars, tattoos, dental work, old injuries, anything unusual.')),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SEARCHING', 'Searching'), ('UNDER_REVIEW', 'A possible match is being reviewed'), ('CONTACTED', 'You have been contacted'), ('RESOLVED', 'Identified'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='registry.event')),
                ('last_seen_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_last_seen', to='registry.region')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='registry.missingpersonreport')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='missingpersonreport',
            index=models.Index(fields=['reporter', '-created_at'], name='registry_mi_reporte_fc55be_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpersonreport',
            index=models.Index(fields=['event', 'status'], name='registry_mi_event_i_ac88c5_idx'),
        ),
    ]
