# Generated by Django 6.1 on 2026-09-05 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_missingpersonreport_reportphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidentifiedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custody_reference', models.CharField(help_text='The reference your facility holds this person under.', max_length=64)),
                ('estimated_age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Not known')], default='UNKNOWN', max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, help_text='Measured, not estimated, where possible.', null=True)),
                ('build', models.CharField(choices=[('SLIGHT', 'Slight'), ('MEDIUM', 'Medium'), ('HEAVY', 'Heavy'), ('UNKNOWN', 'Not known')], default='UNKNOWN', max_length=10)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_location', models.CharField(blank=True, max_length=200)),
                ('clothing_description', models.TextField(blank=True)),
                ('distinguishing_marks', models.TextField(blank=True, help_text='Scars, tattoos, dental work, amputations, old fractures.')),
                ('status', models.CharField(choices=[('HELD', 'Held, unidentified'), ('UNDER_REVIEW', 'A possible match is being reviewed'), ('IDENTIFIED', 'Identified'), ('RELEASED', 'Released to family')], default='HELD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='registry.event')),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_filed', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='registry.organisation')),
                ('recovery_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records_recovered', to='registry.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restricted/records/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='registry.unidentifiedrecord')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unidentifiedrecord',
            index=models.Index(fields=['organisation', '-created_at'], name='registry_un_organis_a0069c_idx'),
        ),
        migrations.AddIndex(
            model_name='unidentifiedrecord',
            index=models.Index(fields=['event', 'status'], name='registry_un_event_i_b55129_idx'),
        ),
        migrations.AddConstraint(
            model_name='unidentifiedrecord',
            constraint=models.UniqueConstraint(fields=('organisation', 'custody_reference'), name='unique_custody_reference_per_organisation'),
        ),
    ]
