# Generated by Django 6.1 on 2026-09-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_unidentifiedrecord_recordphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='flow_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
