# Generated by Django 6.1 on 2026-09-05 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_region_flow_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('score_breakdown', models.JSONField(default=dict)),
                ('score_reasons', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('SUGGESTED', 'Suggested by the engine'), ('UNDER_REVIEW', 'Claimed by a verifier'), ('FAMILY_CONTACTED', 'Family contacted'), ('CONFIRMED', 'Confirmed the same person'), ('REJECTED', 'Not the same person'), ('SUPERSEDED', 'Closed because the other side matched elsewhere')], default='SUGGESTED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='registry.event')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='registry.unidentifiedrecord')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='registry.missingpersonreport')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['event', 'state', '-score'], name='registry_ma_event_i_793aa1_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'record'), name='unique_match_pair')],
            },
        ),
    ]
